"""Credit assessment output model."""
import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import TYPE_CHECKING, Any, Dict, Optional
from sqlalchemy import (
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Uuid,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import JSON
from app.models.base import Base, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.application import Application
    from app.models.model_version import ModelVersion


class RiskLevel(str, enum.Enum):
    """Categorical risk tiers for credit assessment."""

    LOWER = "LOWER"
    MODERATE = "MODERATE"
    HIGHER = "HIGHER"
    INSUFFICIENT = "INSUFFICIENT"


class CreditAssessment(Base, UUIDPrimaryKeyMixin):
    """Output evaluation generated by PARAKH credit assessment engine.

    Fields support NULL values when there is insufficient historical or platform evidence.
    """

    __tablename__ = "credit_assessments"
    __table_args__ = (
        CheckConstraint(
            "credit_score IS NULL OR credit_score >= 0",
            name="check_positive_credit_score",
        ),
        CheckConstraint(
            "risk_probability IS NULL OR (risk_probability >= 0 AND risk_probability <= 1)",
            name="check_risk_probability_range",
        ),
        CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="check_confidence_range",
        ),
    )

    application_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("applications.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    model_version_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("model_versions.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )

    # Core scores and indicators (Nullable for INSUFFICIENT evidence)
    credit_score: Mapped[Optional[int]] = mapped_column(
        Integer,
        nullable=True,
    )
    risk_probability: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 4),
        nullable=True,
    )
    risk_level: Mapped[RiskLevel] = mapped_column(
        Enum(RiskLevel, native_enum=False, length=50),
        nullable=False,
    )
    confidence: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 4),
        nullable=True,
    )
    debt_to_income: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 4),
        nullable=True,
    )
    utilization: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 4),
        nullable=True,
    )
    income_stability: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 4),
        nullable=True,
    )
    repayment_reliability: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(5, 4),
        nullable=True,
    )
    # Structured explainability metadata (TreeSHAP factors, missing signals, diagnostics)
    explanation: Mapped[Optional[Dict[str, Any]]] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=True,
    )
    assessment_status: Mapped[str] = mapped_column(
        String(50),
        default="COMPLETED",
        nullable=False,
    )

    assessed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    # Relationships
    application: Mapped["Application"] = relationship(
        "Application",
        back_populates="credit_assessments",
    )
    model_version: Mapped["ModelVersion"] = relationship(
        "ModelVersion",
        back_populates="credit_assessments",
    )
