"""Dedicated storage service for persistent applicant document files."""
import os
import re
import uuid
from pathlib import Path
from typing import Optional, Union
from app.core.config import settings
from app.services.exceptions import ValidationError


def sanitize_filename(filename: str) -> str:
    """Sanitize original filename to prevent directory traversal and remove unsafe characters.

    Args:
        filename: Raw input filename.

    Returns:
        Sanitized safe base filename.
    """
    if not filename:
        return "document"
    # Extract only base filename, stripping any directories
    base = os.path.basename(filename).strip()
    # Replace non-alphanumeric (except dot, dash, underscore) with underscore
    safe = re.sub(r"[^\w\.\-]", "_", base)
    # Collapse multiple dots or underscores
    safe = re.sub(r"\.{2,}", ".", safe)
    safe = re.sub(r"_{2,}", "_", safe)
    return safe.strip("._") or "document"


class DocumentStorageService:
    """Service managing persistent disk storage for applicant documents.

    Maintains separation between filesystem operations and database persistence.
    Guarantees isolation by application_id and prevents path traversal vulnerabilities.
    """

    def __init__(self, base_dir: Optional[str] = None) -> None:
        """Initialize DocumentStorageService with configured base storage directory."""
        configured_dir = base_dir or settings.UPLOAD_DIR
        try:
            os.makedirs(configured_dir, exist_ok=True)
            self.base_dir = os.path.abspath(configured_dir)
        except (PermissionError, OSError):
            # Fallback to local uploads directory if system path is not writable (e.g. host test runner)
            fallback = os.path.abspath("uploads/documents")
            os.makedirs(fallback, exist_ok=True)
            self.base_dir = fallback

    def _resolve_safe_application_dir(self, application_id: Union[uuid.UUID, str]) -> str:
        """Validate application_id and return absolute directory path inside base_dir.

        Raises:
            ValidationError: If application_id is invalid or attempts path traversal.
        """
        app_id_str = str(application_id).strip()
        # Enforce valid UUID pattern to strictly prevent traversal characters
        try:
            parsed_uuid = uuid.UUID(app_id_str)
            clean_app_id = str(parsed_uuid)
        except ValueError:
            raise ValidationError(f"Invalid application identifier: '{app_id_str}'.")

        target_dir = os.path.abspath(os.path.join(self.base_dir, "applications", clean_app_id))
        # Verify target is strictly within base_dir
        if not target_dir.startswith(self.base_dir) or os.path.commonpath([target_dir, self.base_dir]) != self.base_dir:
            raise ValidationError("Path traversal attempt detected in application directory.")

        os.makedirs(target_dir, exist_ok=True)
        return target_dir

    def generate_stored_filename(
        self,
        document_id: Union[uuid.UUID, str],
        original_filename: str,
        detected_extension: Optional[str] = None,
    ) -> str:
        """Generate a collision-free stored filename prepending document UUID.

        Example:
            original: 'bank_statement.pdf' -> stored: '<uuid>_bank_statement.pdf'
        """
        safe_orig = sanitize_filename(original_filename)
        clean_doc_id = str(document_id).strip()
        
        # If detected_extension provided, ensure safe extension matches
        if detected_extension:
            ext = detected_extension.lower().lstrip(".")
            if not safe_orig.lower().endswith(f".{ext}"):
                safe_orig = f"{safe_orig}.{ext}"

        return f"{clean_doc_id}_{safe_orig}"

    def save_file(
        self,
        application_id: Union[uuid.UUID, str],
        stored_filename: str,
        content: bytes,
    ) -> str:
        """Save file bytes to persistent volume storage within application isolation folder.

        Args:
            application_id: Application UUID.
            stored_filename: Safe stored filename generated by generate_stored_filename.
            content: Raw file binary content.

        Returns:
            str: Absolute file path on disk.

        Raises:
            ValidationError: If stored_filename is unsafe or path traversal is attempted.
        """
        app_dir = self._resolve_safe_application_dir(application_id)
        clean_filename = os.path.basename(stored_filename).strip()
        if not clean_filename or clean_filename != stored_filename:
            raise ValidationError("Unsafe filename detected for persistent storage.")

        target_path = os.path.abspath(os.path.join(app_dir, clean_filename))
        if not target_path.startswith(app_dir) or os.path.commonpath([target_path, app_dir]) != app_dir:
            raise ValidationError("Path traversal attempt detected in target file path.")

        with open(target_path, "wb") as f:
            f.write(content)

        return target_path

    def file_exists(
        self,
        application_id: Union[uuid.UUID, str],
        stored_filename: str,
    ) -> bool:
        """Check whether a stored file exists within the application directory."""
        try:
            app_dir = self._resolve_safe_application_dir(application_id)
            clean_filename = os.path.basename(stored_filename).strip()
            target_path = os.path.abspath(os.path.join(app_dir, clean_filename))
            return os.path.isfile(target_path)
        except Exception:
            return False

    def get_file_path(
        self,
        application_id: Union[uuid.UUID, str],
        stored_filename: str,
    ) -> str:
        """Retrieve verified absolute file path for a stored document.

        Raises:
            FileNotFoundError: If the document does not exist on disk.
        """
        app_dir = self._resolve_safe_application_dir(application_id)
        clean_filename = os.path.basename(stored_filename).strip()
        target_path = os.path.abspath(os.path.join(app_dir, clean_filename))
        if not os.path.isfile(target_path):
            raise FileNotFoundError(f"Stored document '{clean_filename}' does not exist on disk.")
        return target_path

    def delete_file(self, file_path: str) -> bool:
        """Remove a stored file during transaction rollback or deletion.

        Args:
            file_path: Absolute path to the file to delete.

        Returns:
            bool: True if removed or already absent, False on error.
        """
        if not file_path:
            return True
        try:
            resolved = os.path.abspath(file_path)
            # Ensure path is strictly within base_dir before removing
            if resolved.startswith(self.base_dir) and os.path.isfile(resolved):
                os.remove(resolved)
            return True
        except OSError:
            return False
