"""Authoritative feature derivation logic for PARAKH credit risk assessment.

Re-exports pure mathematical derivation functions from the authoritative feature derivation
layer (src.data.synthetic.feature_derivation) ensuring complete parity between training
and runtime serving pipelines without formula duplication.
"""
from src.data.synthetic.feature_derivation import (
    calculate_active_days_ratio,
    calculate_buffer_to_loan,
    calculate_burn_months,
    calculate_consecutive_drops,
    calculate_downside_variance,
    calculate_dti_ratios,
    calculate_group_count,
    calculate_income_cv,
    calculate_interaction_features,
    calculate_iqr_ratio,
    calculate_loan_to_income,
    calculate_max_drawdown,
    calculate_max_idle_streak,
    calculate_mean_income,
    calculate_median_income,
    calculate_min_max_ratio,
    calculate_missing_ratio,
    calculate_net_margin,
    calculate_p25_income,
    calculate_recovery_metrics,
    calculate_trend_momentum,
    calculate_trend_slope,
    calculate_trimmed_mean_income,
    calculate_trips_completed,
    calculate_weekend_intensity,
    calculate_zero_earning_weeks,
    derive_application_features,
    validate_derived_features,
)

__all__ = [
    "calculate_active_days_ratio",
    "calculate_buffer_to_loan",
    "calculate_burn_months",
    "calculate_consecutive_drops",
    "calculate_downside_variance",
    "calculate_dti_ratios",
    "calculate_group_count",
    "calculate_income_cv",
    "calculate_interaction_features",
    "calculate_iqr_ratio",
    "calculate_loan_to_income",
    "calculate_max_drawdown",
    "calculate_max_idle_streak",
    "calculate_mean_income",
    "calculate_median_income",
    "calculate_min_max_ratio",
    "calculate_missing_ratio",
    "calculate_net_margin",
    "calculate_p25_income",
    "calculate_recovery_metrics",
    "calculate_trend_momentum",
    "calculate_trend_slope",
    "calculate_trimmed_mean_income",
    "calculate_trips_completed",
    "calculate_weekend_intensity",
    "calculate_zero_earning_weeks",
    "derive_application_features",
    "validate_derived_features",
]
