"""Centralized audit event and action constants for PARAKH."""

class AuditAction:
    """Standardized action identifiers for security and business audit events."""

    # Authentication & Session
    LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    LOGIN_FAILURE = "AUTH_LOGIN_FAILURE"
    AUTH_FAILURE = "AUTH_FAILURE"
    LOGOUT = "AUTH_LOGOUT"
    ACCESS_DENIED = "AUTH_ACCESS_DENIED"
    OWNERSHIP_VIOLATION = "AUTH_OWNERSHIP_VIOLATION"

    # User Management
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"

    # Applicant Profile
    APPLICANT_PROFILE_CREATED = "APPLICANT_PROFILE_CREATED"
    APPLICANT_PROFILE_UPDATED = "APPLICANT_PROFILE_UPDATED"

    # Application Lifecycle
    APPLICATION_CREATED = "APPLICATION_CREATED"
    APPLICATION_UPDATED = "APPLICATION_UPDATED"
    APPLICATION_STATUS_CHANGED = "APPLICATION_STATUS_CHANGED"

    # Consent Operations
    CONSENT_GRANTED = "CONSENT_GRANTED"
    CONSENT_REVOKED = "CONSENT_REVOKED"

    # Financial Signal
    FINANCIAL_SIGNAL_CREATED = "FINANCIAL_SIGNAL_CREATED"
    FINANCIAL_SIGNAL_ACCESSED = "FINANCIAL_SIGNAL_ACCESSED"

    # Assessment
    ASSESSMENT_EXECUTED = "ASSESSMENT_EXECUTED"
    ASSESSMENT_ACCESSED = "ASSESSMENT_ACCESSED"

    # Model Version
    MODEL_VERSION_CREATED = "MODEL_VERSION_CREATED"
    MODEL_VERSION_ACCESSED = "MODEL_VERSION_ACCESSED"
    MODEL_VERSION_ACTIVATED = "MODEL_VERSION_ACTIVATED"

    # Human Review
    REVIEW_CREATED = "REVIEW_CREATED"
    REVIEW_ACCESSED = "REVIEW_ACCESSED"


class AuditOutcome:
    """Standard outcomes for audit events."""

    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    DENIED = "DENIED"
